# Generated by Django 4.2.7 on 2024-02-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('your_message', models.CharField(max_length=180)),
            ],
        ),
    ]
